
var loadData = function(){

Students.insert({grade:6,name: "BAEK Sheng-Min (Michael)",studentID:58867,advisor:"Fox, Jebediah"})
Students.insert({grade:6,name: "BHAGAT Ankita",studentID:53599,advisor:"Fox, Jebediah"})
Students.insert({grade:6,name: "CHENG Ho-Man (Jonatha)",studentID:58641,advisor:"Fox, Jebediah"})
Students.insert({grade:6,name: "CHIA Rayden Qi-Da",studentID:57513,advisor:"Fox, Jebediah"})
Students.insert({grade:6,name: "HAH Zachary",studentID:53264,advisor:"Fox, Jebediah"})
Students.insert({grade:6,name: "KWONG Wing-Ki",studentID:52412,advisor:"Fox, Jebediah"})
Students.insert({grade:6,name: "LAI Kylie",studentID:59984,advisor:"Fox, Jebediah"})
Students.insert({grade:6,name: "LESKINEN Anni",studentID:60899,advisor:"Fox, Jebediah"})
Students.insert({grade:6,name: "LIVIO Alessandro",studentID:54634,advisor:"Fox, Jebediah"})
Students.insert({grade:6,name: "OH Se-Hyun",studentID:59256,advisor:"Fox, Jebediah"})
Students.insert({grade:6,name: "ROBERTS Timothy",studentID:60831,advisor:"Fox, Jebediah"})
Students.insert({grade:6,name: "ROBERTS Zoe",studentID:60825,advisor:"Fox, Jebediah"})
Students.insert({grade:6,name: "XU Catherine",studentID:56454,advisor:"Fox, Jebediah"})
Students.insert({grade:6,name: "AL-AWADHI Mohammed",studentID:60926,advisor:"Sanchez, Pedro Andres"})
Students.insert({grade:6,name: "DATWANI Dev",studentID:53462,advisor:"Sanchez, Pedro Andres"})
Students.insert({grade:6,name: "DO NGOC Ha-Vi",studentID:59008,advisor:"Sanchez, Pedro Andres"})
Students.insert({grade:6,name: "FANG Howell",studentID:55332,advisor:"Sanchez, Pedro Andres"})
Students.insert({grade:6,name: "GU William",studentID:57335,advisor:"Sanchez, Pedro Andres"})
Students.insert({grade:6,name: "KIM Min-Ju",studentID:60776,advisor:"Sanchez, Pedro Andres"})
Students.insert({grade:6,name: "LEE Jina",studentID:59933,advisor:"Sanchez, Pedro Andres"})
Students.insert({grade:6,name: "LO Chi-Ho(Victor)",studentID:60008,advisor:"Sanchez, Pedro Andres"})
Students.insert({grade:6,name: "PARK Jun-Seo (Ben)",studentID:58736,advisor:"Sanchez, Pedro Andres"})
Students.insert({grade:6,name: "REESE Camila",studentID:58219,advisor:"Sanchez, Pedro Andres"})
Students.insert({grade:6,name: "RUPCHANDANI Vinisha",studentID:52892,advisor:"Sanchez, Pedro Andres"})
Students.insert({grade:6,name: "SALEHI Mobin",studentID:55829,advisor:"Sanchez, Pedro Andres"})
Students.insert({grade:6,name: "TIN Chun-Yu",studentID:57064,advisor:"Sanchez, Pedro Andres"})
Students.insert({grade:7,name: "AL-AWADHI Manar",studentID:60925,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "CHEN Sophie",studentID:57877,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "HO Andrew",studentID:59390,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "JASHNANI Sahil",studentID:54695,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "JUNG Seung Yeon (Angela)",studentID:55935,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "KAWASAKI Yuta",studentID:51371,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "KIM Tae Hyeon",studentID:60203,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "KISHORE Apoorva",studentID:60789,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "KOVALENKO Vadim",studentID:60721,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "MAHENDRU Shivansh",studentID:60274,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "MEI Alan",studentID:57582,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "NAGATANI Shouei",studentID:57537,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "PARK Hyun-Seo",studentID:59931,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "PARK Kyung-Bin",studentID:60351,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "RAO Sanchia Petrina",studentID:60743,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "TAN Gabriel",studentID:58040,advisor:"Haag, Jacob"})
Students.insert({grade:7,name: "BEATRIX Justin",studentID:56520,advisor:"Reuwer, Terrence"})
Students.insert({grade:7,name: "BEELEN Alessandra",studentID:52832,advisor:"Reuwer, Terrence"})
Students.insert({grade:7,name: "FREISSMUTH Benjamin Antonius",studentID:60439,advisor:"Reuwer, Terrence"})
Students.insert({grade:7,name: "HARWANI Diya",studentID:60632,advisor:"Reuwer, Terrence"})
Students.insert({grade:7,name: "HERBET Candice Marie- Lucie",studentID:60545,advisor:"Reuwer, Terrence"})
Students.insert({grade:7,name: "KANG Jun-Yu",studentID:59453,advisor:"Reuwer, Terrence"})
Students.insert({grade:7,name: "LIN Jonathan",studentID:60272,advisor:"Reuwer, Terrence"})
Students.insert({grade:7,name: "LIN Long",studentID:59255,advisor:"Reuwer, Terrence"})
Students.insert({grade:7,name: "MARINO Pietro",studentID:58512,advisor:"Reuwer, Terrence"})
Students.insert({grade:7,name: "OUYANG Simon Long-Hao",studentID:60679,advisor:"Reuwer, Terrence"})
Students.insert({grade:7,name: "PARK Ji-Young",studentID:57617,advisor:"Reuwer, Terrence"})
Students.insert({grade:7,name: "RIMMER Lea",studentID:60702,advisor:"Reuwer, Terrence"})
Students.insert({grade:7,name: "SUNDAR Vaisheswini Saanjh",studentID:55674,advisor:"Reuwer, Terrence"})
Students.insert({grade:7,name: "VIJ Lakshita",studentID:57401,advisor:"Reuwer, Terrence"})
Students.insert({grade:8,name: "BAPNA Tanay",studentID:52403,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "CHAN Curtis",studentID:52613,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "CHEN Gallen",studentID:59638,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "CHUNG Seo Yeon",studentID:60313,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "ENGLUND Vivie",studentID:58620,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "KHANCHANDANI Anjila",studentID:52200,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "KIL Kyung-Min (John)",studentID:56739,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "KIM Hyun-Je",studentID:57572,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "KIM Taeuk",studentID:60202,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "MAENG Ho (David)",studentID:60593,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "NUGENT-HEAD Niame",studentID:57641,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "OHASHI Genya",studentID:60888,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "QIU Jia-Hui",studentID:59784,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "RAETH Moritz",studentID:58159,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "RUGHANI Aanchal",studentID:53525,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "SHIH Hwai- Kang(Patrick)",studentID:59883,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "SHIN Jung-Woo",studentID:58010,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "TAN Choon-Wun",studentID:60642,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "VAN DER EYKEN Felipe",studentID:57453,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "WONG Joie Tiffany",studentID:56570,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "ZHENG Bliss",studentID:56214,advisor:"Payne, Hannah"})
Students.insert({grade:8,name: "ZHOU Andy",studentID:51917,advisor:"Payne, Hannah"})
Students.insert({grade:9,name: "BAE Jun Bo",studentID:55397,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "DUBOIS Apolline Oceane",studentID:60696,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "HUANG Yu-Chieh (Jason)",studentID:58748,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "JIANG Christopher",studentID:59116,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "KANG Tae-Hoon",studentID:60541,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "KIM Hyunjin",studentID:57571,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "LI Cheng-Hao",studentID:60874,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "LI Zheng-Duo(Ana)",studentID:60084,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "LIU Chen-Yu(Lucinda)",studentID:60006,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "LIU Hsuan (Sharon)",studentID:57499,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "MO Yu-Chen(Cameron)",studentID:59998,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "MOELLER Julius",studentID:56153,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "NIESEL Xenia",studentID:52111,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "PARK Jun-Seong",studentID:59932,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "PARK Seung-Bin(Robin)",studentID:58186,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "PARK Seung-Jun(Kevin)",studentID:57623,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "RAO Mrinalini Lianne",studentID:60740,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "TEO Carmen Hui-Ling",studentID:60440,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "WONG Sam Pok-Hin",studentID:52438,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "WU Yu-Chung",studentID:60192,advisor:"Deerwester, Justin"})
Students.insert({grade:9,name: "ZHANG Caroline Zoe",studentID:60267,advisor:"Deerwester, Justin"})
Students.insert({grade:10,name: "AL-AWADHI Ali",studentID:53797,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "CHAN Christy W",studentID:60774,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "CHEUNG Alex",studentID:57534,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "CHIU Tsz-Wai (Suki)",studentID:59033,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "FEI Yi Yang (Annie)",studentID:56594,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "HE Zhong (Rodick)",studentID:60760,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "KANG Jun-Hao",studentID:59452,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "KIM Ye-Sung (Samuel)",studentID:57377,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "KWONG Wing-Lam (Kimmy)",studentID:52017,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "LING Jia-Jun (Jake)",studentID:57312,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "LV Yin-Run (Elena)",studentID:58839,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "PARK Ji- Hwan (Kevin)",studentID:57619,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "RIMMER Vanessa",studentID:60704,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "SALEEM Omar",studentID:60921,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "SHIN Jung-Hwan",studentID:58183,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "YANG Daphine Wan-Jing",studentID:60793,advisor:"Searle, Richard"})
Students.insert({grade:10,name: "ZHENG Cindy",studentID:60949,advisor:"Searle, Richard"})
Students.insert({grade:11,name: "JESUDAS Paul",studentID:57848,advisor:"Weinberg, Evan"})
Students.insert({grade:11,name: "KIM Min-Xiu",studentID:58731,advisor:"Weinberg, Evan"})
Students.insert({grade:11,name: "KIM Noah-San",studentID:60659,advisor:"Weinberg, Evan"})
Students.insert({grade:11,name: "LEE Eun-Bee (Jane)",studentID:57870,advisor:"Weinberg, Evan"})
Students.insert({grade:11,name: "LU Yun-Zhi",studentID:60334,advisor:"Weinberg, Evan"})
Students.insert({grade:11,name: "PARK Jeong-A (Sam)",studentID:57624,advisor:"Weinberg, Evan"})
Students.insert({grade:11,name: "QIU En-Hui (Jessie)",studentID:59785,advisor:"Weinberg, Evan"})
Students.insert({grade:11,name: "ROOTH Maiti",studentID:57502,advisor:"Weinberg, Evan"})
Students.insert({grade:11,name: "SPIEKERMAN Florine",studentID:56322,advisor:"Weinberg, Evan"})
Students.insert({grade:11,name: "WONG Thomas Jim",studentID:56569,advisor:"Weinberg, Evan"})
Students.insert({grade:12,name: "BAPNA Rahul",studentID:52402,advisor:"Rooth, Mary"})
Students.insert({grade:12,name: "BENDER Isaac",studentID:57324,advisor:"Rooth, Mary"})
Students.insert({grade:12,name: "FRIEDMAN Madeline",studentID:59997,advisor:"Rooth, Mary"})
Students.insert({grade:12,name: "HSIAO Yu-Tin(Cherry)",studentID:51702,advisor:"Rooth, Mary"})
Students.insert({grade:12,name: "LIN Christine",studentID:51862,advisor:"Rooth, Mary"})
Students.insert({grade:12,name: "LIU Xue-Fei(Jenny)",studentID:60007,advisor:"Rooth, Mary"})
Students.insert({grade:12,name: "LUK Yan-Ho(Thomas)",studentID:55065,advisor:"Rooth, Mary"})
Students.insert({grade:12,name: "MENG Amy",studentID:57772,advisor:"Rooth, Mary"})
Students.insert({grade:12,name: "MOELLER Jakob",studentID:56152,advisor:"Rooth, Mary"})
Students.insert({grade:12,name: "NUGENT-HEAD Ian",studentID:57642,advisor:"Rooth, Mary"})
Students.insert({grade:12,name: "WANG Meng-Di(Celine)",studentID:60005,advisor:"Rooth, Mary"})
}

Accounts.createUser({username:'eweinberg',password:'12345',email:'eweinberg@scischina.org'},function(e){console.log(e)});
loadData();